services:
  - type: web
    name: langflow
    env: python
    buildCommand: pip install -e .
    startCommand: langflow run --host 0.0.0.0 --port 10000
    envVars:
      - key: LANGFLOW_ENV
        value: production
    plan: free
    autoDeploy: true
    healthCheckPath: /
    region: frankfurt
    runtime: python
    repo: https://github.com/pasvd/langflow
    branch: main
